name: "Create env file"
description: "Github Action to create env file"
inputs:
  variables:
    description: "Keys of environemt variables you want to save into .env file"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
